### ISSUE TITLE
Error ECONNREFUSED

### ISSUE THREAD

**Issue by wsmigielski** [nadavbar/node-spotify-webhelper#10]
Error: connect ECONNREFUSED 127.0.0.1:4370
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 4370 

Keep getting this error

**Comment by dekoci** [comment]
Yeah same, I'm using mac

**Comment by sudhackar** [comment]
#11 Use the changed port and http.
