### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by comfortme** [nadavbar/node-spotify-webhelper#7]
i have been using your node-spotify-webhelper module in windows for a long time now.
but few days ago suddenly it stopped working.
so i think spotify changed some think on their end or updated spotifywebhelper.exe i guess.
i get a "read ECONNRESET" error every time i try to run the code and SpotifyWebHelper.exe crashes shortly after :(

`Error: read ECONNRESET
    at exports._errnoException (util.js:949:11)
    at TLSWrap.onread (net.js:563:26)`

**Comment by sammy8806** [comment]
Yep, I've got the same Problem here.

System Win10 Pro with node 6.3

**Comment by nadavbar** [comment]
The module seems to still work on OSX last time I've checked. What build of windows are you using?

**Comment by comfortme** [comment]
i think it's reletad to latest spotify update for windows. i shifted to port 4371. now it is working again.

**Comment by krisoh** [comment]
i started to use node-spotify-webhelper module and i want to ask you if it works only on localhost or you can use it on application hosted on server?

**Comment by nadavbar** [comment]
You can only use it for localhost. The issue is that it connects to the SpotifyWebHelper process which only listens to localhost. 
Ofcurse, you can always run a node.js server that exposes a web API for the local spotify process.
